title: Psychophysiological Methods in Cognitive Psychology
description: Student-Centered Open Living Textbook by Dr. Yang, Yu-Fang and Students 
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
show_downloads: false
github:
  is_project_page: false
